language: php

notifications:
      email: ivashov@cs.petrsu.ru

branches:
    only:
        - master
        - testing

addons:
    postgresql: "9.3"
    apt:
        packages:
            - python3
php:
    - 5.4

before_script:
    - psql -c 'create database geo2tag;' -U postgres
    - psql -U postgres geo2tag < test/travis/base.pg
    - psql -U postgres geo2tag < db/adminUsers.pg
    - psql -U postgres geo2tag < db/category.pg
    - psql -U postgres geo2tag < db/trustedUsers.pg
    - psql -U postgres geo2tag < db/share.pg
    - psql -U postgres geo2tag < db/json.pg
    - psql -U postgres geo2tag < db/dist.pg
    - cp -f test/travis/config.inc service/include
    - cp -f test/travis/getsconfig.py test

script: bash test/travis/test.sh

